typedef struct __rnqcc_FILE FILE;
extern FILE *stdin;
extern FILE *stdout;
extern FILE *stderr;
int printf(const char *, ...);
int fprintf(FILE *, const char *, ...);
int snprintf(char *, size_t, const char *, ...);
int puts(const char *);
int putchar(int);
int fputs(const char *, FILE *);
int fflush(FILE *);
FILE *fopen(const char *, const char *);
FILE *freopen(const char *, const char *, FILE *);
int fclose(FILE *);
size_t fread(void *, size_t, size_t, FILE *);
size_t fwrite(const void *, size_t, size_t, FILE *);
int fgetc(FILE *);
int fputc(int, FILE *);
char *fgets(char *, int, FILE *);
int fseek(FILE *, long, int);
long ftell(FILE *);
void rewind(FILE *);
int feof(FILE *);
int ferror(FILE *);
void clearerr(FILE *);
void perror(const char *);
int remove(const char *);
int rename(const char *, const char *);
int sscanf(const char *, const char *, ...);
int sprintf(char *, const char *, ...);
int vprintf(const char *, __builtin_va_list);
int vfprintf(FILE *, const char *, __builtin_va_list);
int vsnprintf(char *, size_t, const char *, __builtin_va_list);
